// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

library test_runner.util;

/// Name of the directory that will contain the test files generated by the
/// test runner.
const String GENERATED_TEST_FILES_DIR_NAME = "__test_runner";
